// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuXKM2E9f1_GbMMs4V_fUXaO35PD61x8o',
    appId: '1:1077491622895:web:72b6e54403c88876ddcc1a',
    messagingSenderId: '1077491622895',
    projectId: 'fire-dice-6336a',
    authDomain: 'fire-dice-6336a.firebaseapp.com',
    storageBucket: 'fire-dice-6336a.appspot.com',
    measurementId: 'G-EDR1VMCFCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM7tvyfu8hsRp12SqNifUPEb6HEsaoYFk',
    appId: '1:1077491622895:android:8153bbc53237e373ddcc1a',
    messagingSenderId: '1077491622895',
    projectId: 'fire-dice-6336a',
    storageBucket: 'fire-dice-6336a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUt1J2HLy-DO3Fj-Dp-lfndbtscY7zPEQ',
    appId: '1:1077491622895:ios:f73fd194dd15aa10ddcc1a',
    messagingSenderId: '1077491622895',
    projectId: 'fire-dice-6336a',
    storageBucket: 'fire-dice-6336a.appspot.com',
    iosBundleId: 'com.example.fireDice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUt1J2HLy-DO3Fj-Dp-lfndbtscY7zPEQ',
    appId: '1:1077491622895:ios:b0c64720dee5272bddcc1a',
    messagingSenderId: '1077491622895',
    projectId: 'fire-dice-6336a',
    storageBucket: 'fire-dice-6336a.appspot.com',
    iosBundleId: 'com.example.fireDice.RunnerTests',
  );
}
